export const Maindata = [
  {
    id: 1,
    img: '/pexels-ivan-samkov-8951199 1.webp',
    date: 'January 3, 2023',
    title: 'How to prepare a delicious gluten free sushi',
    header: 'The secret tips & tricks to prepare a perfect burger & pizza for our customers',
    header2: 'What do you need to prepare a home-made Sushi (gluten free)?',
    body: 'Here are the 5 basic things you need to prepare homemade gluten-free sushi:',
    list: '1. Sushi Rice – Short grain rice seasoned with gluten-free rice vinegar.',
    list2: '2. Nori Sheets – Ensure they’re labeled gluten-free.',
    list3: '3. Fillings – Fresh fish, veggies, or cooked seafood (gluten-free).',
    list4: '4. Dipping Sauce – Tamari (gluten-free soy sauce), pickled ginger, wasabi.',
    list5: '5. Tools – Bamboo mat, sharp knife, plastic wrap.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 2,
    img: '/pexels-skyler-ewing-10307512 1.webp',
    date: 'January 3, 2023',
    title: 'Exclusive baking lessons from the pastry king',
    header: 'The secret tips & tricks to prepare a perfect cake like a pro',
    header2: 'What do you need for professional baking at home?',
    body: 'Essential tools and ingredients for top-level baking:',
    list: '1. Accurate Digital Scale – For precise measurements.',
    list2: '2. Quality Bakeware – Non-stick pans and silicone mats.',
    list3: '3. Stand Mixer – Essential for dough and batter.',
    list4: '4. Premium Ingredients – Use fresh dairy, quality flour, real butter.',
    list5: '5. Thermometer – For checking cake doneness and sugar temperature.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 3,
    img: '/pexels-suzy-hazelwood-2966196 1 (2).webp',
    date: 'January 3, 2023',
    title: 'How to prepare the perfect fries in an air fryer',
    header: 'The secret tips & tricks to prepare crispy air fryer fries',
    header2: 'What do you need to prepare air fryer fries?',
    body: 'Follow these basics for the crispiest air fryer fries:',
    list: '1. Potatoes – Russet or Yukon gold, peeled or skin-on.',
    list2: '2. Soaking – Soak slices in cold water for 30 mins.',
    list3: '3. Drying – Pat fries dry to remove moisture.',
    list4: '4. Light Oil – Toss in light olive or avocado oil.',
    list5: '5. Air Fryer Settings – Cook at 375°F, shaking halfway.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 4,
    img: '/pexels-leonardo-luz-13998974 1 (1).webp',
    date: 'January 3, 2023',
    title: 'How to prepare delicious chicken tenders',
    header: 'The secret tips & tricks to make juicy, crispy chicken tenders',
    header2: 'What do you need to prepare chicken tenders?',
    body: 'Key ingredients and steps to prepare perfect tenders:',
    list: '1. Chicken Strips – Fresh, boneless, skinless.',
    list2: '2. Marinade – Buttermilk with seasoning.',
    list3: '3. Breading – Flour, cornstarch, spices.',
    list4: '4. Cooking – Deep fry or air fry until golden.',
    list5: '5. Sauce – Serve with ranch, BBQ, or honey mustard.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 5,
    img: '/pexels-marta-dzedyshko-2067396 1.webp',
    date: 'January 3, 2023',
    title: '5 great cooking gadgets you can buy to save time',
    header: 'Top 5 time-saving kitchen tools you’ll love',
    header2: 'What are the must-have cooking gadgets?',
    body: 'Here are the top gadgets to save you hours in the kitchen:',
    list: '1. Air Fryer – Healthy frying without oil.',
    list2: '2. Instant Pot – Cooks meals in minutes.',
    list3: '3. Food Processor – Quick chopping & blending.',
    list4: '4. Digital Meat Thermometer – Perfect doneness every time.',
    list5: '5. Mandoline Slicer – Even, fast slicing.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 6,
    img: '/pexels-valeria-boltneva-1833337 1.webp',
    date: 'January 3, 2023',
    title: 'The secret tips & tricks to prepare a perfect burger',
    header: 'Ultimate guide to making a restaurant-style burger at home',
    header2: 'What do you need for a perfect home burger?',
    body: 'Make your burger taste like it’s from a gourmet diner:',
    list: '1. Ground Beef – 80/20 blend for juicy results.',
    list2: '2. Seasoning – Salt, pepper, and garlic powder.',
    list3: '3. Buns – Toasted brioche or potato rolls.',
    list4: '4. Toppings – Lettuce, tomato, pickles, onions, cheese.',
    list5: '5. Sauce – Mayo, ketchup, mustard, or custom blend.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 7,
    img: '/pexels-sebastian-coman-photography-3791088 1 (1).webp',
    date: 'January 3, 2023',
    title: '7 delicious cheesecake recipes you can prepare',
    header: 'Cheesecake lovers, these 7 recipes are for you!',
    header2: 'What do you need to prepare cheesecake?',
    body: 'Each of these recipes needs a solid foundation:',
    list: '1. Cream Cheese – Full-fat for creaminess.',
    list2: '2. Crust – Made from crushed biscuits or graham crackers.',
    list3: '3. Sweetener – Sugar or alternative.',
    list4: '4. Toppings – Fruits, chocolate, caramel, etc.',
    list5: '5. Bake or Chill – Decide between baked or no-bake style.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 8,
    img: '/pexels-katerina-holmes-5908226 1.webp',
    date: 'January 3, 2023',
    title: '5 great pizza restaurants you should visit this city',
    header: 'Discover the best pizza spots in your area',
    header2: 'What makes these pizza places stand out?',
    body: 'These restaurants are rated top for a reason:',
    list: '1. Authentic Crust – Wood-fired or artisan made.',
    list2: '2. Fresh Ingredients – Locally sourced toppings.',
    list3: '3. Signature Sauces – House-made tomato or white sauce.',
    list4: '4. Ambience – Cozy spots perfect for casual dining.',
    list5: '5. Unique Flavors – From truffle to spicy honey.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 9,
    img: '/pexels-irina-bogodukhova-9032910 1 (2).webp',
    date: 'January 3, 2023',
    title: '5 great cooking gadgets you can buy to save time',
    header: 'Kitchen gadgets that transform how you cook',
    header2: 'What are the best tools to speed up cooking?',
    body: 'These devices make cooking faster and easier:',
    list: '1. Blender – Great for soups and smoothies.',
    list2: '2. Garlic Press – Skip chopping every time.',
    list3: '3. Electric Griddle – Cook multiple things at once.',
    list4: '4. Egg Cooker – Perfect boiled eggs, no guesswork.',
    list5: '5. Hand Mixer – Faster batter and whipping.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 10,
    img: '/pexels-nishant-aneja-2955819 1.webp',
    date: 'January 3, 2023',
    title: 'How to prepare a delicious gluten free sushi',
    header: 'Master the art of gluten-free sushi making at home',
    header2: 'Essentials for preparing sushi without gluten:',
    body: 'Don’t let gluten stop your sushi cravings!',
    list: '1. Rice – Short-grain, properly seasoned.',
    list2: '2. Nori – Gluten-free certified.',
    list3: '3. Fillings – Fish, veggies, cream cheese (gluten-free).',
    list4: '4. Sauces – Use tamari instead of soy sauce.',
    list5: '5. Tools – Mat, knife, plastic wrap.',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 11,
    img: '/pexels-jan-n-g-u-y-e-n-🍁-2664216 1.webp',
    date: 'January 3, 2023',
    title: 'Top 20 simple and quick desserts for kids',
    header: 'Fun, easy desserts kids can make and love',
    header2: 'What do you need for kid-friendly desserts?',
    body: 'Quick treats that are fun to make and eat:',
    list: '1. No-Bake Cookies – Just mix and chill.',
    list2: '2. Fruit Kabobs – Healthy and colorful.',
    list3: '3. Yogurt Parfaits – Layered with granola and fruit.',
    list4: '4. Chocolate Dipped Anything – Bananas, pretzels, marshmallows.',
    list5: '5. Mug Cakes – Dessert in 90 seconds!',
    header3:'What are the right ingredients to make it delicious?'
  },
  {
    id: 12,
    img: '/pexels-igor-ovsyannykov-205961 1 (1).webp',
    date: 'January 3, 2023',
    title: 'Top 20 simple and quick desserts for kids',
    header: 'Treat your kids with these fun and tasty desserts',
    header2: 'Essentials to prepare these quick treats:',
    body: 'Perfect for birthdays, weekends, or snack time:',
    list: '1. Mini Cupcakes – Use ready-made mix.',
    list2: '2. Rice Krispie Treats – Kids love the crunch.',
    list3: '3. Pudding Cups – Layered with crushed cookies.',
    list4: '4. Fruit Pops – Blend fruit and freeze.',
    list5: '5. Sprinkle Cookies – Bake and decorate together.',
    header3:'What are the right ingredients to make it delicious?'
  }
];
